### ISSUE TITLE
Unique in repeating instrument

### ISSUE THREAD

**Issue by ThomasVermes** [Research-IT-Swiss-TPH/redcap-unique-actiontag#11]
Usecase:

We have a project where in a repeated instrument we would like to register all the operations that a patient has to undergo.
Each OP has a unique ID and I we would like to set there the action tag.
Out of curiosity I tried with this one, but it (as expected) did not worked 
@UNIQUE-STRICT="unique_rep"
tschuus!!

**Comment by SalvoCas** [comment]
Hi, by any chance, have you solved this issue? If so, how? Thank you in advanced.

**Comment by tertek** [comment]
added with PR 88020814b506bc12e037721798f80ca8f80b146a
